---
server:
  port: 8080
  tomcat:
    relaxed-query-chars: [ '[',']' ]
spring:
  profiles:
    active: dev
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${env.DATABASE_USERNAME}
    url: ${env.DATABASE_URL}
    password: ${env.DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: ${env.EMAIL_USERNAME}
    password: ${env.EMAIL_PASSWORD}
    port: 587
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: ${env.OAUTH2_GOOGLE_CLIENT_ID}
#            clientSecret: ${env.OAUTH2_GOOGLE_CLIENT_SECRET}
#            redirectUri: "http://localhost:3005/oauth2/callback/google"
#            scope: email,profile

app:
  aws:
    accessKey: ${env.AWS_ACCESSKEY}
    secretKey: ${env.AWS_SECRETKEY}
    s3Url: ${env.S3_BASE_URL}